#!/usr/bin/env python3

#Task 1

num_1 = int(input("Enter the first number: "))
num_2 = int(input("Enter the second number: "))

sum = num_1 + num_2
print(sum)
dif = num_1 - num_2
print(dif)
product = num_1 * num_2
print(product)
div = num_1/num_2
print(div)
mod = num_1%num_2
print(mod)
